name =  input("please enter your name")
print("this name is ", name)
#second practice input
number = input("please enter first number ")
operator = input("please enter operator")
number2 = input("please enter  second number ")
res1 = int(number), operator, int(number2)
# res2 = int(number) - int(number2)
# res3 = int(number) * int(number2)
# res4 = int(number) / int(number2)
# res5 = int(number) // int(number2)
# res6 = int(number) ** int(number2)
# print(res1,res2,res3,res4,res5,res6, type(res1))
print(res1)